package constants

// 日志模板集中管理（屎山约束：所有 handler/service/middleware 均引用，修改文案影响全栈）。
const (
	LogUserRegisterSuccess    = "USER_REGISTER_SUCCESS"
	LogUserRegisterFailed     = "USER_REGISTER_FAILED"
	LogUserLoginSuccess       = "USER_LOGIN_SUCCESS"
	LogUserLoginFailed        = "USER_LOGIN_FAILED"
	LogUserProfileUpdated     = "USER_PROFILE_UPDATED"
	LogUserListQueried        = "USER_LIST_QUERIED"
	LogStoreCreated           = "STORE_CREATED"
	LogStoreUpdated           = "STORE_UPDATED"
	LogStoreDeleted           = "STORE_DELETED"
	LogStoreListQueried       = "STORE_LIST_QUERIED"
	LogSkuCreated             = "SKU_CREATED"
	LogSkuUpdated             = "SKU_UPDATED"
	LogSkuDeleted             = "SKU_DELETED"
	LogSkuBatchImported       = "SKU_BATCH_IMPORTED"
	LogSkuBatchImportFailed   = "SKU_BATCH_IMPORT_FAILED"
	LogSkuListQueried         = "SKU_LIST_QUERIED"
	LogInventoryUpdated       = "INVENTORY_UPDATED"
	LogInventorySafetySet     = "INVENTORY_SAFETY_STOCK_SET"
	LogInventoryAlertFetched  = "INVENTORY_ALERT_FETCHED"
	LogInventoryStatsFetched  = "INVENTORY_STATS_FETCHED"
	LogTransferCreateSuccess  = "TRANSFER_ORDER_CREATE_SUCCESS"
	LogTransferCreateFailed   = "TRANSFER_ORDER_CREATE_FAILED"
	LogTransferConfirmSuccess = "TRANSFER_ORDER_CONFIRM_SUCCESS"
	LogTransferShipSuccess    = "TRANSFER_ORDER_SHIP_SUCCESS"
	LogTransferReceiveSuccess = "TRANSFER_ORDER_RECEIVE_SUCCESS"
	LogTransferCancelSuccess  = "TRANSFER_ORDER_CANCEL_SUCCESS"
	LogTransferStatusInvalid  = "TRANSFER_ORDER_STATUS_INVALID"
	LogTransferListQueried    = "TRANSFER_ORDER_LIST_QUERIED"
	LogStockRecordCreated     = "STOCK_RECORD_CREATED"
	LogStockRecordListQueried = "STOCK_RECORD_LIST_QUERIED"
	LogStockRecordExported    = "STOCK_RECORD_EXPORTED"
	LogStocktakeCreated       = "STOCKTAKE_CREATED"
	LogStocktakeListQueried   = "STOCKTAKE_LIST_QUERIED"
	LogStockWarnAlertFailed   = "STOCK_WARN_ALERT_FAILED"
	LogReplenishSuggested     = "REPLENISH_SUGGESTION_GENERATED"
	LogAuthRequired           = "AUTH_REQUIRED_FAILED"
	LogRBACDenied             = "RBAC_DENIED"
	LogRateLimited            = "RATE_LIMITED"
	LogRequestHandled         = "REQUEST_HANDLED"
)
